name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: print pdf
      run: |
        chmod +x ./print/getBook.bat
        cd print        
        ./getBook.bat
        copy book.pdf ../docs/ConsoleToSaas.pdf

    - uses: actions/upload-artifact@v1
      with:
        name: ConsoleToSaas.pdf
        path: ./print/book.pdf

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "from GitHub actions" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  # build_pdf:
    
  #   runs-on: windows-latest   
  #   # runs:
  #   #   using: 'docker'
  #   #   image: 'print/exportPDF.txt'
    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: print pdf
  #     run: |
  #       cd print
  #       ./getBook.bat
      
