name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: print pdf
      run: |
        chmod +x ./print/getBook.bat
        cd print        
        ./getBook.bat

    - uses: actions/upload-artifact@v1
      with:
        name: ConsoleToSaas.pdf
        path: ./print/book.pdf

  # build_pdf:
    
  #   runs-on: windows-latest   
  #   # runs:
  #   #   using: 'docker'
  #   #   image: 'print/exportPDF.txt'
    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: print pdf
  #     run: |
  #       cd print
  #       ./getBook.bat
      
