name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: print pdf
      run: |
        chmod +x ./print/getBook.bat
        cd print        
        ./getBook.bat
        cp ./book.pdf ../docs/ConsoleToSaas.pdf

    - uses: actions/upload-artifact@v1
      with:
        name: ConsoleToSaas.pdf
        path: ./print/book.pdf

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "from GitHub actions" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
          
      - uses: docker://pandoc/latex:2.9
        with: # needs a README in your repo root!
          #args: "--standalone --output=output/README.html README.md"
          args: "README.md Chapter01/readme.md --standalone -f markdown -t html --number-sections --toc -o output/output.html"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
  # build_pdf:
    
  #   runs-on: windows-latest   
  #   # runs:
  #   #   using: 'docker'
  #   #   image: 'print/exportPDF.txt'
    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: print pdf
  #     run: |
  #       cd print
  #       ./getBook.bat
      
